### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by BastiLoe** [RUBi-ZA/JMS#2]
I get the server running (after fixes discrebed before) but can't login as the admin user I created:

```
System check identified 1 issue (0 silenced).
November 04, 2017 - 10:52:53
Django version 1.7.1, using settings 'JMS.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[04/Nov/2017 10:53:01] "GET / HTTP/1.1" 302 0
[04/Nov/2017 10:53:01] "GET /account/login?next=/ HTTP/1.1" 200 2809
Internal Server Error: /account/login
Traceback (most recent call last):
  File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/JMS/src/interface/views.py", line 65, in sign_in
    user = authenticate(username=username, password=password)
  File "/srv/JMS/src/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 59, in authenticate
    user = backend.authenticate(**credentials)
  File "/srv/JMS/src/filemanager/backends.py", line 33, in authenticate
    if self.linux_auth(encoded):
  File "/srv/JMS/src/filemanager/backends.py", line 46, in linux_auth
    r = requests.post(self.imp_url, data=data)
  File "/srv/JMS/src/venv/lib/python2.7/site-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/srv/JMS/src/venv/lib/python2.7/site-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/JMS/src/venv/lib/python2.7/site-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/JMS/src/venv/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/srv/JMS/src/venv/lib/python2.7/site-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

**Comment by davidbrownza** [comment]
Hi Bastiloe. This looks like you haven't started the Impersonator service. To start the Impersonator, do the following:
```
sudo su
source src/venv/bin/activate
cd src/impersonator
sh start.sh
```

I am in the process of replacing the built-in impersonator service with this more secure version: https://github.com/Stavatech/Impersonator

I will be releasing an update to JMS soon, which will contain fixes to cater for the trouble you had getting the server running, as well as convert JMS to use the new Impersonator service.

**Comment by davidbrownza** [comment]
We are currently working on a new JMS branch, [2.x-beta](https://github.com/RUBi-ZA/JMS/tree/2.x-beta). As mentioned above, this branch uses a new version on the Impersonator service and fixes a number of know issues in the original branch. Please give this ago and let me know if you are still having similar issue.

We are aware of some lingering issues related to workflows and the job history page is still being reworked, but we would still appreciate any feedback relating to bugs you may find while using JMS.
